### ISSUE TITLE
Button images are missing

### ISSUE THREAD

**Issue by gmeader** [alexmacrae/SamplerBox#1] opened 2017-08-30 22:02 UTC
4 files are required for GUI:

button_left.png
button_right.png
button_enter.png
button_cancel.png

**Comment by alexmacrae** [comment] 2017-08-31 02:47
Hey @gmeader, I've committed these missing graphics (09bc93ad3b230b94e0e4c48f038096c19cf7968b), however they're only useful on a PC, and that's if it's still working as intended (it's been a while since I've touched it). These missing files have no impact on the RPi.

**Closed as completed** 2017-10-05 06:00 UTC
